restrict_ip.settings:
  type: config_object
  label: 'Restrict IP settings'
  constraints:
    FullyValidatable: ~
  mapping:
    enable:
      type: boolean
      label: 'Enable module'
    mail_address:
      type: email
      label: 'Contact mail address to show to blocked users'
    dblog:
      type: boolean
      label: 'Log blocked access attempts'
    allow_role_bypass:
      type: boolean
      label: 'Allow IP blocking to be bypassed by roles'
    bypass_action:
      type: string
      label: 'Action to perform for blocked users when bypassing by role is enabled'
      constraints:
        Choice:
          - provide_link_login_page
          - redirect_login_page
    white_black_list:
      type: integer
      label: 'Whether to use a path whitelist, blacklist, or check all pages'
      constraints:
        Choice:
          - 0
          - 1
          - 2
    country_white_black_list:
      type: integer
      label: 'Whether to use a whitelist, blacklist, or neither for countries'
      constraints:
        Choice:
          - 0
          - 1
          - 2
    country_list:
      type: string
      label: 'A colon separated list of countries that should be white/black listed'
      nullable: true
      constraints:
        CountryCode: []